name: Multiple Jobs

on: push

jobs: 
    build_job1:
        #needs: test_job2
        # do not include same job in the needs section, because it will creates a cycle in the dependency graph. 
        # we also need to run workflow at least one job with no dependencies. 
        runs-on: ubuntu-latest
        steps:      
        - name: install cowsay program
          run: sudo apt-get install cowsay -y

        - name: Generate  ASCII Artwork
          run: cowsay -f dragon "Run for Cover, I am a DRAGON ....." >> dragon.txt

        - name: Upload an artifact 
          uses: actions/upload-artifact@v4
          with:
            # Name of the artifact to upload.
            # Optional. Default is 'artifact'
            name: dragon-text-file           
            # A file, directory or wildcard pattern that describes what to upload
            # Required.
            path: dragon.txt

    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        steps:
        - name: Download an artifact 
          uses: actions/download-artifact@v4
          with:
            # Name of the artifact to download.
            # Optional. Default is 'artifact'
            name: dragon-text-file         
            
        - name: Test file exists
          run: grep -i "dragon" dragon.txt       

    deploy_job3:
        needs: test_job2
        runs-on: ubuntu-latest
        steps:     
        - name: Download an artifact 
          uses: actions/download-artifact@v4
          with:
           # Name of the artifact to download.
           # Optional. Default is 'artifact'
           name: dragon-text-file  

        - name: Read file
          run: cat dragon.txt
        
        - name: deployment
          run: echo "deploymnet is in progress"
        
        
        