name: Run Shell Script

on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: list repo files
          run: ls -ltra

        - name: install cowsay program
          run: ./ascii-generation.sh
        
      
           
        
        
        